# Replace the primary mouse cursor with a transparent one to hide it better.
#
# Transparent cursor file grabbed from https://github.com/celly/transparent-xcursor
#
# JMP is supposed to be hiding the cursor for us, but it doesn't properly do so all the time.
# I initially tried just throwing moving the mouse to the bottom-right, but that left 1 visible white pixel.
# This 1 pixel means the TV doesn't detect a blank screen, causing issues for auto powersaving functions.
#
# Phoc is also supposed to hide the cursor when there's no mouse attached (since it's a touch-based compositor)
# but I've never seen that actually work.
# I suspect that never triggers because the IR stuff is creating a virtual mouse input,
# not really bothered looking into it that much.
[Icon Theme]
Inherits=invisible
