[[protocols]]
name = "TBS"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x9f = "KEY_EXIT"
0x84 = "KEY_CLOSE"  # This is the power button, set to this for compatibility with the PrisonPC remote, and because systemd sees KEY_POWER and shuts down
0x94 = "KEY_MUTE"
# FIXME: Really all of these numbers should be KEY_NUMERIC_* but those don't actually work
#        Fallback should be KEY_KP* but I can't get numlock forced on, so they don't work either
#        With this config '#' doesn't work at all, but everything else is fine, this is good enough.
0x87 = "KEY_1"
0x86 = "KEY_2"
0x85 = "KEY_3"
0x8b = "KEY_4"
0x8a = "KEY_5"
0x89 = "KEY_6"
0x8f = "KEY_7"
0x8e = "KEY_8"
0x8d = "KEY_9"
0xd1 = "KEY_CONNECT"  # Should probably be KPASTERISK, but this is for consistency with the PrisonPC remote where I've configured CONNECT as an extra play/pause button
0x92 = "KEY_0"
0xd2 = "KEY_NUMERIC_POUND"
0x80 = "KEY_BACK"
0xd4 = "KEY_CLEAR"
0x81 = "KEY_UP"
0x90 = "KEY_LEFT"
0x99 = "KEY_ENTER"
0x82 = "KEY_RIGHT"
0x88 = "KEY_DOWN"
0x96 = "KEY_CHANNELUP"
0x91 = "KEY_CHANNELDOWN"
0x93 = "KEY_VOLUMEUP"
0x8c = "KEY_VOLUMEDOWN"
0xdd = "KEY_TV"
0x9d = "KEY_F11"  # KEY_ZOOM would make more sense, but this has greater consistency with "fullscreen" buttons on other remotes
0x95 = "KEY_FAVORITES"
0x9b = "KEY_MODE"
0x9e = "KEY_MENU"
0x9c = "KEY_EPG"
0x97 = "KEY_SUBTITLE"
0x9a = "KEY_SYSRQ"  # PrintScreen
0x83 = "KEY_RECORD"
0xde = "KEY_PLAYCD"
0x98 = "KEY_PAUSECD"
0xdc = "KEY_STOPCD"
0xdb = "KEY_REWIND"
0xda = "KEY_FASTFORWARD"
0xd9 = "KEY_PREVIOUSSONG"
0xd8 = "KEY_NEXTSONG"
