[[protocols]]
name = "TBS"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x9f = "KEY_EXIT"
0x84 = "KEY_CLOSE"  # This is the power button, set to this for compatibility with the PrisonPC remote, and because systemd sees KEY_POWER and shuts down
0x94 = "KEY_MUTE"
0x87 = "KEY_KP1"
0x86 = "KEY_KP2"
0x85 = "KEY_KP3"
0x8b = "KEY_KP4"
0x8a = "KEY_KP5"
0x89 = "KEY_KP6"
0x8f = "KEY_KP7"
0x8e = "KEY_KP8"
0x8d = "KEY_KP9"
0xd1 = "KEY_KPASTERISK"
0x92 = "KEY_PLAYPAUSE"  # Should be KP0, but this remote's layout sucks so I want an easy-to-find play/pause button
0xd2 = "KEY_NUMERIC_POUND"
0x80 = "KEY_BACK"
0xd4 = "KEY_CLEAR"
0x81 = "KEY_UP"
0x90 = "KEY_LEFT"
0x99 = "KEY_ENTER"
0x82 = "KEY_RIGHT"
0x88 = "KEY_DOWN"
0x96 = "KEY_CHANNELUP"
0x91 = "KEY_CHANNELDOWN"
0x93 = "KEY_VOLUMEUP"
0x8c = "KEY_VOLUMEDOWN"
0xdd = "KEY_TV"
0x9d = "KEY_ZOOM"
0x95 = "KEY_FAVORITES"
0x9b = "KEY_MODE"
0x9e = "KEY_MENU"
0x9c = "KEY_EPG"
0x97 = "KEY_SUBTITLE"
0x9a = "KEY_SYSRQ"  # PrintScreen
0x83 = "KEY_RECORD"
0xde = "KEY_PLAYCD"
0x98 = "KEY_PAUSECD"
0xdc = "KEY_STOPCD"
0xdb = "KEY_REWIND"
0xda = "KEY_FASTFORWARD"
0xd9 = "KEY_PREVIOUSSONG"
0xd8 = "KEY_NEXTSONG"
